[package]
name = "syntax_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.8.1"
prettytable = "0.10"
ron = "0.10.1"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
